export const sidebarEndpoints = {
  "Dashboard": "/tasks/statistics/dashboard",
  "Add new task": "just wanted the key and the structure",
  "Customize tasks": "just wanted the key and the structure",
  "Completed tasks": "/tasks/status/completed",
  "In Progress tasks": "/tasks/status/in-progress",
  "In Pending tasks": "/tasks/status/pending",
  "High prority tasks": "/tasks/priority/high",
  "Medium prority tasks": "/tasks/priority/medium",
  "Low prority tasks": "/tasks/priority/low",
  "Get tasks posted within 3 days": "/tasks/posted?days=3",
  "Get tasks posted within 10 days": "/tasks/posted?days=10",
  "Get tasks posted within 30 days": "/tasks/posted?days=30",
  "Get tasks posted after 30 days": "/tasks/posted?days=31",
  "Get tasks updated within 3 days": "/tasks/updated?days=3",
  "Get tasks updated within 10 days": "/tasks/updated?days=10",
  "Get tasks updated within 30 days": "/tasks/updated?days=30",
  "Get tasks updated after 30 days": "/tasks/updated?days=31",
  "Get tasks deleted within 3 days": "/tasks/deleted?days=3",
  "Get tasks deleted within 10 days": "/tasks/deleted?days=10",
  "Get tasks deleted within 30 days": "/tasks/deleted?days=30",
  "Get tasks deleted after 30 days": "/tasks/deleted?days=31",
  Logout: "/api/auth/logout",
};
